### ISSUE TITLE
Make apium configurable to support multiple REST APIs 

### ISSUE THREAD

**Issue by jamescoq** [lundegaard/apium#1]
Currently apium supports only one REST API base url. 

It would be nice to be able to use apium with several different REST api base urls at once.
The easiest way how to achieve that seem to be to add `baseUrl` attribute into request action payload and then modify this url composition:
https://github.com/lundegaard/apium/blob/eb269e85a9bd543930e349d87a7a73a412106120/packages/apium/src/middleware.js#L72

however this is from my perspective the quickies solution. Not very conceptual.

**Comment by wafflepie** [comment]
Allowing `request` actions to accept `baseUrl` in the payload is a pretty good enhancement in my opinion, but not necessarily one you'd wanna use to tackle your problem anyway.

Instead, what you can do is pass a custom `transformRequestAction` function when configuring the middleware. This would allow you to dynamically modify the `url` based on any condition.

```js
const servers = {
  foo: 'http://localhost:8001/foo',
  bar: 'http://localhost:8002/bar',
}

makeApiumMiddleware({
  transformRequestAction: action => ({
    ...action,
    payload: {
      ...action.payload,
      url: servers[action.payload.server] + action.payload.url
  })
})

dispatch(request({ url: '/my-endpoint', server: 'foo' })) // http://localhost:8001/foo/my-endpoint
```

Obviously, this would mean passing no `baseUrl` to configure Apium at all and instead using `transformRequestAction` only.
